version: '3'
services:

  # as docker image
  # sbt docker:stage
  # docker-compose build
  # docker-compose up -d web
  # webimg:
  #   build: ./target/docker/stage/
  #   ports:
  #     - "8080:8080"
  #   env_file:
  #     - /etc/environment
  #   environment:
  #     MONGO_URL_BILLS_TRACKER: mongodb://root:secret@mongo:27017/admin
  #   links:
  #     - mongo
  #   depends_on:
  #     - mongo

  # without own image
  # sbt stage
  # docker-compose up -d web
  web:
    image: oracle/graalvm-ce:19.2.0
    ports:
      - 8080:8080
      - 8000:8000
    env_file:
      - /etc/environment
    environment:
      MONGO_URL_BILLS_TRACKER: mongodb://root:secret@mongo:27017/admin
      JAVA_OPTS: "-Xdebug -Xrunjdwp:server=y,transport=dt_socket,suspend=n,address=8000"
    links:
      - mongo
    depends_on:
      - mongo
    volumes:
    - ./target/universal/stage/:/home/billstracker
    command: /home/billstracker/bin/billstracker

  mongo:
    image: mongo:3.6
    restart: always
    command: --smallfiles
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: secret
    volumes:
      - ./cache/mongodata:/data/db
    ports:
      - 27017:27017

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: secret
    depends_on:
      - mongo
